aid1807正式班老师课件/Django/Day06/DjangoDemo06/index/urls.py
from django.conf.urls import url
from .views import *
urlpatterns = [
  url(r'^01-request/$',request_views),
  url(r'^02-request/$',request02_views),
  url(r'^03-post/$',post_views),
  url(r'^04-all/$',all_views),
  url(r'^05-register/$',register_views),
  url(r'^06-form/$',form_views),
]

aid1807正式班老师课件/Django/Day06/DjangoDemo06/index/forms.py
from django import forms

#声明ChoiceField要用到的数据
TOPIC_CHOICE = (
  ('1','好评'),
  ('2','中评'),
  ('3','差评'),
)

#表示评论内容的表单控件的class
#控件1-评论标题-文本框
#控件2-电子邮箱-邮件框
#控件3-评论内容-Textarea
#控件4-评论级别-下拉选择框
#控件5-是否保存-复选框
class RemarkForm(forms.Form):
  #评论标题
  # forms.CharField() - 文本框
  # label : 控件前的文本标签
  subject = forms.CharField(label='标题')
  #电子邮箱
  # forms.EmailField() - Email框
  # label : 控件前的文本标签
  email = forms.EmailField(label='邮箱')
  #品论内容
  # widget=Textarea : 将当前的单行文本框变为多行文本域
  message = forms.CharField(label='内容',widget=forms.Textarea)
  #品论级别
  # forms.ChoiceField() - 下拉列表框
  # choices : 表示当前下拉列表框中的数据,取值为元组或列表
  topic = forms.ChoiceField(label='级别',choices=TOPIC_CHOICE)
  #是否保存-复选框
  isSaved = forms.BooleanField(label='是否保存')

aid1807正式班老师课件/Django/Day06/DjangoDemo06/index/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from index.forms import RemarkForm
from index.models import Author


def request_views(request):
  scheme = request.scheme
  body = request.body
  path = request.path
  full_path = request.get_full_path()
  host = request.get_host()
  method = request.method
  post = request.POST
  get = request.GET
  cookies = request.COOKIES
  meta = request.META
  return render(request,'01-request.html',locals())

def request02_views(request):
  year = request.GET.get('year','1900')
  month = request.GET.get('month','01')
  day = request.GET.get('day','01')
  print("传递的数据:%s年%s月%s日" % (year,month,day))
  return HttpResponse('Get OK')

def post_views(request):
  if request.method == 'GET':
    return render(request,'03-post.html')
  else:
    uname = request.POST.get('uname')
    upwd = request.POST.get('upwd')
    return HttpResponse("用户名:%s,用户密码:%s" % (uname,upwd))

def all_views(request):
  authors = Author.objects.all()
  for au in authors:
    print(au.id,au.name,au.age,au.email)
  return HttpResponse("Query OK")

def register_views(request):
  if request.method == 'GET':
    return render(request,'05-register.html')
  else:
    #接收前端传递过来的数据
    name = request.POST.get('name')
    age = request.POST.get('age')
    email = request.POST.get('email')
    #将数据封装成 author 的对象
    au = Author()
    au.name = name
    au.age = age
    au.email = email
    #调用author的save()将数据保存进数据库
    au.save()
    return HttpResponse("Register OK")

def form_views(request):
  if request.method == 'GET':
    #创建RemarkForm的对象,并发送到06-form.html中
    form = RemarkForm()
    return render(request,'06-form.html',locals())
  else:
    subject = request.POST.get('subject')
    email = request.POST.get('email')
    message = request.POST.get('message')
    topic = request.POST.get('topic')
    isSaved = request.POST.get('isSaved','0')
    return HttpResponse("Subject:%s,Email:%s,Message:%s,Topic:%s,IsSaved:%s" % (subject,email,message,topic,isSaved))

aid1807正式班老师课件/Django/Day06/DjangoDemo06/templates/06-form.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <style>
    #id_subject{
      border:none;
      border-bottom:1px solid #000;
      outline:none;
    }
  </style>
</head>
<body>
{% comment '手动解析' %}
<form action="/06-form/" method="post">
  {% csrf_token %}
  {% for field in form %}
    <p>
      {{ field.label }}:{{ field }}
    </p>
  {% endfor %}
  <p>
    <input type="submit">
  </p>
</form>
{% endcomment %}

{% comment '自动解析- {{ form.as_p }}' %}
<form action="/06-form/" method="post">
  {{ form.as_p }}
  <p>
    <input type="submit">
  </p>
</form>
{% endcomment %}

{% comment '自动解析- {{ form.as_ul }}' %}
<form action="/06-form/" method="post">
  <ol>
    {{ form.as_ul }}
    <li>
      <input type="submit">
    </li>
  </ol>
</form>
{% endcomment %}

<form action="/06-form/" method="post">
  <table>
    {{ form.as_table }}
  </table>
</form>
</body>
</html>